# Generated by Django 4.2.5 on 2023-09-10 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_admingroup_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalJigyosyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='jigyosyo',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LogicalJigyosyoAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('merge', 'Merge'), ('split', 'Split')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_jigyosyos', models.ManyToManyField(related_name='related_actions', to='crm.jigyosyo')),
                ('logical_jigyosyo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='crm.logicaljigyosyo')),
            ],
        ),
        migrations.AddField(
            model_name='logicaljigyosyo',
            name='jigyosyos',
            field=models.ManyToManyField(related_name='logical_groups', to='crm.jigyosyo'),
        ),
        migrations.AddField(
            model_name='logicaljigyosyo',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_representative_for', to='crm.jigyosyo'),
        ),
    ]
