# Generated by Django 4.2.5 on 2023-09-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
        ('crm', '0003_logicaljigyosyo_jigyosyo_type_logicaljigyosyoaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigyosyo',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jigyosyos', to='crm.company'),
        ),
        migrations.AlterField(
            model_name='jigyosyo',
            name='crawl_list_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jigyosyo', to='crawler.crawllist'),
        ),
    ]
