# Generated by Django 4.2.5 on 2023-09-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlList',
            fields=[
                ('jigyosyo_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jigyosyo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('kourou_jigyosyo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fetch_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crawl_list',
            },
        ),
        migrations.CreateModel(
            name='CrawlDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_datetime', models.DateTimeField(blank=True, null=True)),
                ('jigyosyo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.crawllist')),
            ],
            options={
                'db_table': 'crawl_detail',
            },
        ),
    ]
